
services:
  bitcoin-mainnet:
    build: .
    volumes:
      - ${MAINNET_NODE_DIR}:/bitcoin
    command: ["-datadir=/bitcoin", "-conf=/bitcoin/bitcoin.conf"]
    ports:
      - "${MAINNET_RPC_PORT}:${MAINNET_RPC_PORT}"
      - "${MAINNET_P2P_PORT}:${MAINNET_P2P_PORT}"
      - "${MAINNET_ZMQ_BLOCK_PORT}:${MAINNET_ZMQ_BLOCK_PORT}"   # ZMQ block
      - "${MAINNET_ZMQ_TX_PORT}:${MAINNET_ZMQ_TX_PORT}"   # ZMQ tx
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bitcoin-net

  bitcoin-testnet:
    build: .
    volumes:
      - ${TESTNET_NODE_DIR}:/bitcoin
    command: ["-datadir=/bitcoin", "-conf=/bitcoin/bitcoin.conf"]
    ports:
      - "${TESTNET_RPC_PORT}:${TESTNET_RPC_PORT}"
      - "${TESTNET_P2P_PORT}:${TESTNET_P2P_PORT}"
      - "${TESTNET_ZMQ_BLOCK_PORT}:${TESTNET_ZMQ_BLOCK_PORT}"   # ZMQ block
      - "${TESTNET_ZMQ_TX_PORT}:${TESTNET_ZMQ_TX_PORT}"   # ZMQ tx
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bitcoin-net

  rpc-proxy:
    build: ./rpc-proxy
    environment:
      - RPC_PROXY_PORT=${RPC_PROXY_PORT}
      - RPC_ACCESS_TOKEN=${RPC_ACCESS_TOKEN}
      - RPC_MAINNET_URL=${RPC_MAINNET_URL}
      - RPC_TESTNET_URL=${RPC_TESTNET_URL}
      - RPC_MAINNET_AUTH=${RPC_MAINNET_AUTH}
      - RPC_TESTNET_AUTH=${RPC_TESTNET_AUTH}
    ports:
      - "${RPC_PROXY_PORT}:${RPC_PROXY_PORT}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - bitcoin-mainnet
      - bitcoin-testnet
    networks:
      - bitcoin-net

  # api-proxy:
  #   build: ./api-proxy/
  #   environment:
  #     - ESPLORA_MAINNET_URL=${RPC_ACCESS_TOKEN}
  #     - ESPLORA_TESTNET_URL=${RPC_MAINNET_NODE_URL}
  #     - ESPLORA_PROXY_PORT=${ESPLORA_PROXY_PORT}
  #   ports:
  #     - "${ESPLORA_PROXY_PORT}:${ESPLORA_PROXY_PORT}"
  #   restart: unless-stopped
  #   depends_on:
  #     - esplora-mainnet
  #     - esplora-testnet4
  #   networks:
  #     - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge
